packages:
  - playground

minimumReleaseAge: 4320 # 3 Days
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
minimumReleaseAgeExclude:
  # Renovate security update: vite@7.3.5
  - vite@7.3.5
